#!/usr/bin/expect

#Usage sshsudologin.expect <host> <ssh user> <ssh password> <su user> <su password>

set timeout 60

spawn ssh [lindex $argv 0]@[lindex $argv 2]

expect "yes/no" {
	send "yes\r"
	expect "*?assword" { send "[lindex $argv 1]\r" }
	} "*?assword" { send "[lindex $argv 1]\r" }


expect "DBAUDIT*" {
    send "maintaince\r"
    expect "*?assword" {
        send "[lindex $argv 3]\r"
        expect "sh*" {
            send "sudo su root -\r"
                expect -re ".*#" {
                    send "cat /proc/net/pf_ring/5244-eth0.1|grep -i 'Tot Packets'|awk -F: '{print \$2}'|sed 's/ //g' \r"
                    expect -re ".*#" {
                    regexp {(\n)(\d.*)} "$expect_out(buffer)" matched
                    #puts stdout  "matched : \ $matched \n"
                    set result $matched
                    }
                    puts stdout  "result: $result"
                    #return $result
                    #interact
                }
            }

        }

    }