#!/usr/bin/expect

#Usage sshsudologin.expect <host> <ssh user> <ssh password> <su user> <su password>

set timeout 60

spawn ssh [lindex $argv 0]@[lindex $argv 2]

expect "yes/no" {
	send "yes\r"
	expect "*?assword" { send "[lindex $argv 1]\r" }
	} "*?assword" { send "[lindex $argv 1]\r" }


expect "DBAUDIT*" {
    send "maintaince\r"
    expect "*?assword" {
        send "[lindex $argv 3]\r"
        expect "sh*" {
            send "sudo su root -\r"
                expect -re ".*#" {
                    send "cat /proc/net/pf_ring/3653-eth0.1|grep -i -A 2 -B 2 'Tot Packets' \r"
                    expect -re ".*#" {
                    }
                    #interact
                }
            }

        }

    }